# Generated by Django 2.2.4 on 2019-08-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190809_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingUP',
        ),
    ]
