# Generated by Django 2.2.4 on 2019-08-06 07:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=250)),
                ('logo', models.ImageField(upload_to='api-logos/')),
                ('description', models.TextField()),
                ('officialapi', models.BooleanField(default=True)),
                ('github', models.URLField()),
                ('email', models.EmailField(max_length=200, null=True)),
                ('twitter', models.URLField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='ApiList',
        ),
    ]
