# Generated by Django 2.2.4 on 2019-08-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190806_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
